on:
  push:
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11.0.6
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.6

    - name: Build with Maven
      run: mvn package
      env:
        GITHUB_TOKEN: ${{ github.token }}
