on:
  push:
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11.0.6
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.6

    - run: mvn clean install --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}

    - name: Deploy to GitHub Packages
      run: mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }} --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
